# Generated by Django 5.0.4 on 2024-05-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operateur', '0015_claim_heure'),
    ]

    operations = [
        migrations.CreateModel(
            name='firewall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Claim',
        ),
    ]
