# Generated by Django 5.0.4 on 2024-05-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operateur', '0018_sdwan'),
    ]

    operations = [
        migrations.CreateModel(
            name='SDWANRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=15)),
                ('members', models.CharField(max_length=15)),
                ('fortigate', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='sdwan',
            name='fortigate',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
